service: hello-world

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev

package:
  patterns:
    - '!.idea/**'
    - '!docs/**'

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true